import { Anton_SC, Inter } from "next/font/google";
import "./globals.css";
import 'leaflet/dist/leaflet.css';
import 'leaflet-routing-machine/dist/leaflet-routing-machine.css';
import Script from "next/script";
import { Toaster } from "sonner";
import ClientWrapper from "@/wrapper/ClientWrapper";

const anton = Anton_SC({
  variable: "--font-anton",
  weight: "400",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/images/favicon.png",
  },
  verification: {
    google: "",
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${anton.variable} ${inter.variable} font-sans antialiased`}
      >
        <Toaster position="top-right" />
        <ClientWrapper>
          {children}
        </ClientWrapper>
        <Script
          type="module"
          src="https://cdn.jsdelivr.net/npm/ldrs/dist/auto/dotPulse.js"
          strategy="afterInteractive"
        />
      </body>
    </html>
  );
}
