'use client'

import { useState } from "react";
import { useMachinery } from "@/context/useMachinery";
import {
    Breadcrumb,
    BreadcrumbItem,
    BreadcrumbLink,
    BreadcrumbList,
    BreadcrumbPage,
    BreadcrumbSeparator,
} from "@/components/ui/breadcrumb"
import { Input } from "@/components/ui/input";
import {
    DropdownMenu,
    DropdownMenuContent,
    DropdownMenuItem,
    DropdownMenuLabel,
    DropdownMenuSeparator,
    DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu"
import {
    Pagination,
    PaginationContent,
    PaginationEllipsis,
    PaginationItem,
    PaginationLink,
    PaginationNext,
    PaginationPrevious,
} from "@/components/ui/pagination"
import {
    Accordion,
    AccordionContent,
    AccordionItem,
    AccordionTrigger,
} from "@/components/ui/accordion"
import { Checkbox } from "@/components/ui/checkbox"
import { Label } from "@/components/ui/label"
import { Button } from "@/components/ui/button"
import { ArrowDownAZ, ArrowDownNarrowWide, ArrowDownWideNarrow, ArrowUpAZ, ArrowUpDown, ClockArrowDown, ClockArrowUp, SlidersHorizontal, X } from "lucide-react"
import ProductCard from "@/components/ProductCard";
import { Slider } from "@/components/ui/slider";

// export const metadata = {
//     title: 'Listings',
//     description: 'Generated by create next app',
// }

function page() {
    const { machinery } = useMachinery()
    const [priceRange, setPriceRange] = useState([0, 100]);


    return (
        <>
            <section className="sm:min-h-48 min-h-40 bg-[url('/images/listing-bg.jpg')] bg-cover bg-center bg-no-repeat flex justify-center
            items-center relative">
                <div className="absolute bg-yellow-500/20 backdrop-blur-[2px] inset-0"></div>
                <div className="h-full w-full flex flex-col justify-center items-center relative z-10 space-y-2">
                    <h1 className="text-white text-3xl font-semibold">Listings</h1>
                    <Breadcrumb>
                        <BreadcrumbList>
                            <BreadcrumbItem>
                                <BreadcrumbLink href="/" className={'text-gray-400 hover:text-yellowClr'}>Home</BreadcrumbLink>
                            </BreadcrumbItem>
                            <BreadcrumbSeparator />
                            <BreadcrumbItem>
                                <BreadcrumbPage className={'text-gray-300'}>Listings</BreadcrumbPage>
                            </BreadcrumbItem>
                        </BreadcrumbList>
                    </Breadcrumb>
                </div>
            </section>
            <section className="bg-neutral-700 md:px-6 px-4">
                <div className="grid lg:grid-cols-5 md:grid-cols-4 sm:gap-4 gap-2">
                    <div className="md:block hidden h-fit top-16 sticky border-r border-neutral-700 py-6 pe-4">
                        <div className="flex justify-between items-start mb-2">
                            <p className="text-yellowClr font-medium">FILTERS</p>
                            <Button variant={'outline'} className="text-xs h-7 px-2 gap-1"><X className="h-4" /> Clear</Button>
                        </div>
                        <div>
                            <div className="border-b border-neutral-700 py-2 text-white">
                                <p className="font-semibold text-sm">Price Range</p>
                                <div className="space-y-4 mb-2">
                                    <div>
                                        <output className="w-full text-sm font-medium tabular-nums flex justify-between">
                                            <span>₹{priceRange[0]}</span>
                                            <span>₹{priceRange[1]}</span>
                                        </output>
                                    </div>
                                    <Slider
                                        value={priceRange}
                                        min={21}
                                        max={100}
                                        onValueChange={setPriceRange}
                                        onValueCommit={(val) => {
                                            const [min, max] = val
                                            const params = new URLSearchParams(searchParams.toString())
                                            params.set('minAge', min)
                                            params.set('maxAge', max)
                                            router.replace(`/matrimony-profiles?${params.toString()}`, {
                                                scroll: false,
                                            })
                                        }}
                                        aria-label="Dual range slider for Age"
                                    />
                                </div>
                            </div>
                            <Accordion
                                type="single"
                                collapsible
                                className="w-full border-b border-neutral-700"
                            >
                                <AccordionItem value="item-1">
                                    <AccordionTrigger className={'text-white! font-semibold'}>Category</AccordionTrigger>
                                    <AccordionContent className="flex flex-col gap-3 text-balance text-white!">
                                        <div className="flex items-center gap-2">
                                            <Checkbox id="bulldozer" />
                                            <Label htmlFor="bulldozer">Bulldozer</Label>
                                        </div>
                                        <div className="flex items-center gap-2">
                                            <Checkbox id="crane" />
                                            <Label htmlFor="crane">Crane</Label>
                                        </div>
                                        <div className="flex items-center gap-2">
                                            <Checkbox id="trucks" />
                                            <Label htmlFor="trucks">Trucks</Label>
                                        </div>
                                    </AccordionContent>
                                </AccordionItem>
                            </Accordion>
                            <div className="py-2 text-white">
                                <p className="font-semibold text-sm">Distance</p>
                                <div className="space-y-4 mb-2">
                                    <div>
                                        <output className="w-full text-sm font-medium tabular-nums flex justify-between">
                                            <span>{priceRange[0]}<span className="text-xs">km</span></span>
                                            <span>{priceRange[1]}<span className="text-xs">km</span></span>
                                        </output>
                                    </div>
                                    <Slider
                                        value={priceRange}
                                        min={21}
                                        max={100}
                                        onValueChange={setPriceRange}
                                        onValueCommit={(val) => {
                                            const [min, max] = val
                                            const params = new URLSearchParams(searchParams.toString())
                                            params.set('minAge', min)
                                            params.set('maxAge', max)
                                            router.replace(`/matrimony-profiles?${params.toString()}`, {
                                                scroll: false,
                                            })
                                        }}
                                        aria-label="Dual range slider for Age"
                                    />
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className="lg:col-span-4 md:col-span-3 py-6">
                        <div className="bg-neutral-700 pb-4 flex sm:flex-row flex-col justify-between sm:items-start gap-2 md:static sticky top-[72px]">
                            <div>
                                <p className="text-white text-xl font-semibold">All Listings</p>
                                <p className="text-sm text-gray-400">Showing 10 of 1,000 listings</p>
                            </div>
                            <div className="flex gap-2">
                                <Input type="text" className={'bg-white focus-visible:ring-0 focus-visible:border-yellowClr'} placeholder="Search" />
                                <DropdownMenu modal={false}>
                                    <DropdownMenuTrigger asChild>
                                        <Button className="gap-2">
                                            <ArrowUpDown className="w-4 h-4" />
                                            <span className="sm:inline hidden">Sort by</span>
                                        </Button>
                                    </DropdownMenuTrigger>

                                    <DropdownMenuContent align="end" className="w-48">

                                        <DropdownMenuItem >
                                            <ClockArrowDown className="w-4 h-4" />
                                            Newest to Oldest
                                        </DropdownMenuItem>

                                        <DropdownMenuItem >
                                            <ClockArrowUp className="w-4 h-4" />
                                            Oldest to Newest
                                        </DropdownMenuItem>

                                        <DropdownMenuSeparator />

                                        <DropdownMenuItem>
                                            <ArrowDownNarrowWide className="w-4 h-4" />
                                            Price: Low to High
                                        </DropdownMenuItem>

                                        <DropdownMenuItem>
                                            <ArrowDownWideNarrow className="w-4 h-4" />
                                            Price: High to Low
                                        </DropdownMenuItem>

                                        <DropdownMenuSeparator />

                                        <DropdownMenuItem >
                                            <ArrowDownAZ className="w-4 h-4" />
                                            Name: A to Z
                                        </DropdownMenuItem>

                                        <DropdownMenuItem >
                                            <ArrowUpAZ className="w-4 h-4" />
                                            Name: Z to A
                                        </DropdownMenuItem>
                                    </DropdownMenuContent>
                                </DropdownMenu>
                            </div>
                        </div>
                        <div className="grid lg:grid-cols-4 md:grid-cols-3 sm:grid-cols-2 sm:gap-4 gap-2">
                            {machinery?.map((item, index) => (
                                <ProductCard key={index} data={item} />
                            ))}
                        </div>
                        <Pagination className={'mt-6 text-white'}>
                            <PaginationContent>
                                <PaginationItem>
                                    <PaginationPrevious href="#" />
                                </PaginationItem>
                                <PaginationItem>
                                    <PaginationLink href="#" isActive>1</PaginationLink>
                                </PaginationItem>
                                <PaginationItem>
                                    <PaginationLink href="#">2</PaginationLink>
                                </PaginationItem>
                                <PaginationItem>
                                    <PaginationLink href="#">3</PaginationLink>
                                </PaginationItem>
                                <PaginationItem>
                                    <PaginationNext href="#" />
                                </PaginationItem>
                            </PaginationContent>
                        </Pagination>
                    </div>
                </div>
            </section>
        </>
    )
}

export default page
