// 'use client'

// import { useState } from "react";
// import { useMachinery } from "@/context/useMachinery";
// import {
//     Breadcrumb,
//     BreadcrumbItem,
//     BreadcrumbLink,
//     BreadcrumbList,
//     BreadcrumbPage,
//     BreadcrumbSeparator,
// } from "@/components/ui/breadcrumb"
// import { Input } from "@/components/ui/input";
// import {
//     DropdownMenu,
//     DropdownMenuContent,
//     DropdownMenuItem,
//     DropdownMenuLabel,
//     DropdownMenuSeparator,
//     DropdownMenuTrigger,
// } from "@/components/ui/dropdown-menu"
// import {
//     Pagination,
//     PaginationContent,
//     PaginationEllipsis,
//     PaginationItem,
//     PaginationLink,
//     PaginationNext,
//     PaginationPrevious,
// } from "@/components/ui/pagination"
// import {
//     Accordion,
//     AccordionContent,
//     AccordionItem,
//     AccordionTrigger,
// } from "@/components/ui/accordion"
// import { Checkbox } from "@/components/ui/checkbox"
// import { Label } from "@/components/ui/label"
// import { Button } from "@/components/ui/button"
// import { ArrowDownAZ, ArrowDownNarrowWide, ArrowDownWideNarrow, ArrowUpAZ, ArrowUpDown, ClockArrowDown, ClockArrowUp, SlidersHorizontal, X } from "lucide-react"
// import ProductCard from "@/components/ProductCard";
// import { Slider } from "@/components/ui/slider";

// // export const metadata = {
// //     title: 'Listings',
// //     description: 'Generated by create next app',
// // }

// function page() {
//     const { machinery } = useMachinery()
//     const [priceRange, setPriceRange] = useState([0, 100]);


//     return (
//         <>
//             <section className="sm:min-h-48 min-h-40 bg-[url('/images/listing-bg.jpg')] bg-cover bg-center bg-no-repeat flex justify-center
//             items-center relative">
//                 <div className="absolute bg-yellow-500/20 backdrop-blur-[2px] inset-0"></div>
//                 <div className="h-full w-full flex flex-col justify-center items-center relative z-10 space-y-2">
//                     <h1 className="text-white text-3xl font-semibold">Listings</h1>
//                     <Breadcrumb>
//                         <BreadcrumbList>
//                             <BreadcrumbItem>
//                                 <BreadcrumbLink href="/" className={'text-gray-400 hover:text-yellowClr'}>Home</BreadcrumbLink>
//                             </BreadcrumbItem>
//                             <BreadcrumbSeparator />
//                             <BreadcrumbItem>
//                                 <BreadcrumbPage className={'text-gray-300'}>Listings</BreadcrumbPage>
//                             </BreadcrumbItem>
//                         </BreadcrumbList>
//                     </Breadcrumb>
//                 </div>
//             </section>
//             <section className="bg-neutral-700 md:px-6 px-4">
//                 <div className="grid lg:grid-cols-5 md:grid-cols-4 sm:gap-4 gap-2">
//                     <div className="md:block hidden h-fit top-16 sticky border-r border-neutral-700 py-6 pe-4">
//                         <div className="flex justify-between items-start mb-2">
//                             <p className="text-yellowClr font-medium">FILTERS</p>
//                             <Button variant={'outline'} className="text-xs h-7 px-2 gap-1"><X className="h-4" /> Clear</Button>
//                         </div>
//                         <div>
//                             <div className="border-b border-neutral-700 py-2 text-white">
//                                 <p className="font-semibold text-sm">Price Range</p>
//                                 <div className="space-y-4 mb-2">
//                                     <div>
//                                         <output className="w-full text-sm font-medium tabular-nums flex justify-between">
//                                             <span>₹{priceRange[0]}</span>
//                                             <span>₹{priceRange[1]}</span>
//                                         </output>
//                                     </div>
//                                     <Slider
//                                         value={priceRange}
//                                         min={21}
//                                         max={100}
//                                         onValueChange={setPriceRange}
//                                         onValueCommit={(val) => {
//                                             const [min, max] = val
//                                             const params = new URLSearchParams(searchParams.toString())
//                                             params.set('minAge', min)
//                                             params.set('maxAge', max)
//                                             router.replace(`/matrimony-profiles?${params.toString()}`, {
//                                                 scroll: false,
//                                             })
//                                         }}
//                                         aria-label="Dual range slider for Age"
//                                     />
//                                 </div>
//                             </div>
//                             <Accordion
//                                 type="single"
//                                 collapsible
//                                 className="w-full border-b border-neutral-700"
//                             >
//                                 <AccordionItem value="item-1">
//                                     <AccordionTrigger className={'text-white! font-semibold'}>Category</AccordionTrigger>
//                                     <AccordionContent className="flex flex-col gap-3 text-balance text-white!">
//                                         <div className="flex items-center gap-2">
//                                             <Checkbox id="bulldozer" />
//                                             <Label htmlFor="bulldozer">Bulldozer</Label>
//                                         </div>
//                                         <div className="flex items-center gap-2">
//                                             <Checkbox id="crane" />
//                                             <Label htmlFor="crane">Crane</Label>
//                                         </div>
//                                         <div className="flex items-center gap-2">
//                                             <Checkbox id="trucks" />
//                                             <Label htmlFor="trucks">Trucks</Label>
//                                         </div>
//                                     </AccordionContent>
//                                 </AccordionItem>
//                             </Accordion>
//                             <div className="py-2 text-white">
//                                 <p className="font-semibold text-sm">Distance</p>
//                                 <div className="space-y-4 mb-2">
//                                     <div>
//                                         <output className="w-full text-sm font-medium tabular-nums flex justify-between">
//                                             <span>{priceRange[0]}<span className="text-xs">km</span></span>
//                                             <span>{priceRange[1]}<span className="text-xs">km</span></span>
//                                         </output>
//                                     </div>
//                                     <Slider
//                                         value={priceRange}
//                                         min={21}
//                                         max={100}
//                                         onValueChange={setPriceRange}
//                                         onValueCommit={(val) => {
//                                             const [min, max] = val
//                                             const params = new URLSearchParams(searchParams.toString())
//                                             params.set('minAge', min)
//                                             params.set('maxAge', max)
//                                             router.replace(`/matrimony-profiles?${params.toString()}`, {
//                                                 scroll: false,
//                                             })
//                                         }}
//                                         aria-label="Dual range slider for Age"
//                                     />
//                                 </div>
//                             </div>
//                         </div>
//                     </div>
//                     <div className="lg:col-span-4 md:col-span-3 py-6">
//                         <div className="bg-neutral-700 pb-4 flex sm:flex-row flex-col justify-between sm:items-start gap-2 md:static sticky top-[72px]">
//                             <div>
//                                 <p className="text-white text-xl font-semibold">All Listings</p>
//                                 <p className="text-sm text-gray-400">Showing 10 of 1,000 listings</p>
//                             </div>
//                             <div className="flex gap-2">
//                                 <Input type="text" className={'bg-white focus-visible:ring-0 focus-visible:border-yellowClr'} placeholder="Search" />
//                                 <DropdownMenu modal={false}>
//                                     <DropdownMenuTrigger asChild>
//                                         <Button className="gap-2">
//                                             <ArrowUpDown className="w-4 h-4" />
//                                             <span className="sm:inline hidden">Sort by</span>
//                                         </Button>
//                                     </DropdownMenuTrigger>

//                                     <DropdownMenuContent align="end" className="w-48">

//                                         <DropdownMenuItem >
//                                             <ClockArrowDown className="w-4 h-4" />
//                                             Newest to Oldest
//                                         </DropdownMenuItem>

//                                         <DropdownMenuItem >
//                                             <ClockArrowUp className="w-4 h-4" />
//                                             Oldest to Newest
//                                         </DropdownMenuItem>

//                                         <DropdownMenuSeparator />

//                                         <DropdownMenuItem>
//                                             <ArrowDownNarrowWide className="w-4 h-4" />
//                                             Price: Low to High
//                                         </DropdownMenuItem>

//                                         <DropdownMenuItem>
//                                             <ArrowDownWideNarrow className="w-4 h-4" />
//                                             Price: High to Low
//                                         </DropdownMenuItem>

//                                         <DropdownMenuSeparator />

//                                         <DropdownMenuItem >
//                                             <ArrowDownAZ className="w-4 h-4" />
//                                             Name: A to Z
//                                         </DropdownMenuItem>

//                                         <DropdownMenuItem >
//                                             <ArrowUpAZ className="w-4 h-4" />
//                                             Name: Z to A
//                                         </DropdownMenuItem>
//                                     </DropdownMenuContent>
//                                 </DropdownMenu>
//                             </div>
//                         </div>
//                         <div className="grid lg:grid-cols-4 md:grid-cols-3 sm:grid-cols-2 sm:gap-4 gap-2">
//                             {machinery?.map((item, index) => (
//                                 <ProductCard key={index} data={item} />
//                             ))}
//                         </div>
//                         <Pagination className={'mt-6 text-white'}>
//                             <PaginationContent>
//                                 <PaginationItem>
//                                     <PaginationPrevious href="#" />
//                                 </PaginationItem>
//                                 <PaginationItem>
//                                     <PaginationLink href="#" isActive>1</PaginationLink>
//                                 </PaginationItem>
//                                 <PaginationItem>
//                                     <PaginationLink href="#">2</PaginationLink>
//                                 </PaginationItem>
//                                 <PaginationItem>
//                                     <PaginationLink href="#">3</PaginationLink>
//                                 </PaginationItem>
//                                 <PaginationItem>
//                                     <PaginationNext href="#" />
//                                 </PaginationItem>
//                             </PaginationContent>
//                         </Pagination>
//                     </div>
//                 </div>
//             </section>
//         </>
//     )
// }

// export default page




"use client";

import { useState, useEffect, useMemo } from "react";
import { useMachinery } from "@/context/useMachinery";
import { getAllMachinery } from "@/api/machineryApis";
import {
    Breadcrumb,
    BreadcrumbItem,
    BreadcrumbLink,
    BreadcrumbList,
    BreadcrumbPage,
    BreadcrumbSeparator,
} from "@/components/ui/breadcrumb";
import { Input } from "@/components/ui/input";
import {
    DropdownMenu,
    DropdownMenuContent,
    DropdownMenuItem,
    DropdownMenuSeparator,
    DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import {
    Pagination,
    PaginationContent,
    PaginationEllipsis,
    PaginationItem,
    PaginationLink,
    PaginationNext,
    PaginationPrevious,
} from "@/components/ui/pagination";
import {
    Accordion,
    AccordionContent,
    AccordionItem,
    AccordionTrigger,
} from "@/components/ui/accordion";
import { Checkbox } from "@/components/ui/checkbox";
import { Label } from "@/components/ui/label";
import { Button } from "@/components/ui/button";
import {
    ArrowDownAZ,
    ArrowDownNarrowWide,
    ArrowDownWideNarrow,
    ArrowUpAZ,
    ArrowUpDown,
    ClockArrowDown,
    ClockArrowUp,
    X,
} from "lucide-react";
import ProductCard from "@/components/ProductCard";
import { Slider } from "@/components/ui/slider";

const ITEMS_PER_PAGE = 12;

function Page() {
    const context = useMachinery();
    const [machinery, setMachinery] = useState([]);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState(null);

    // -------- Filter state --------
    const [priceRange, setPriceRange] = useState([0, 10000]);
    const [selectedCategories, setSelectedCategories] = useState([]);
    const [searchQuery, setSearchQuery] = useState("");
    const [distanceRange, setDistanceRange] = useState([0, 500]); // mock for now
    const [sortBy, setSortBy] = useState("newest"); // newest, oldest, price_asc, price_desc, name_asc, name_desc

    // Pagination
    const [currentPage, setCurrentPage] = useState(1);

    // -------- Categories extracted from data (dynamic) --------
    const [availableCategories, setAvailableCategories] = useState([]);

    // -------- Favorites --------
    const [favorites, setFavorites] = useState([]);
    useEffect(() => {
        const stored = localStorage.getItem("ekcors_favorites");
        if (stored) setFavorites(JSON.parse(stored));
    }, []);
    useEffect(() => {
        localStorage.setItem("ekcors_favorites", JSON.stringify(favorites));
    }, [favorites]);

    const toggleFavorite = (machine) => {
        setFavorites((prev) => {
            const exists = prev.some((item) => item._id === machine._id);
            if (exists) return prev.filter((item) => item._id !== machine._id);
            return [...prev, machine];
        });
    };
    const isFavorite = (id) => favorites.some((item) => item.id === id);

    // Fetch machinery
    useEffect(() => {
        const fetchData = async () => {
            setLoading(true);
            setError(null);
            try {
                if (context && context.machinery && context.machinery.length > 0) {
                    setMachinery(context.machinery);
                } else {
                    const response = await getAllMachinery();
                    console.log("API RESPONSE 👉", response);
                    // const data = response?.data?.machinery || [];
                    const data = response?.data?.machinery || [];
                    // const data = response?.data?.data?.machinery || [];
                    setMachinery(data);
                }
            } catch (err) {
                console.error(err);
                setError("Failed to load machinery. Please try again.");
            } finally {
                setLoading(false);
            }
        };
        fetchData();
    }, [context]);

    // Extract unique categories when machinery loads
    useEffect(() => {
        if (machinery.length) {
            const cats = [...new Set(machinery.map((item) => item.category).filter(Boolean))];
            setAvailableCategories(cats);
        }
    }, [machinery]);

    // Reset page when filters change
    useEffect(() => {
        setCurrentPage(1);
    }, [priceRange, selectedCategories, searchQuery, sortBy]);

    // Helper: filter machinery
    const filteredMachinery = useMemo(() => {
        let filtered = [...machinery];

        // Price filter
        // filtered = filtered.filter(
        //     (item) =>
        //         item.dailyCapPrice >= priceRange[0] && item.dailyCapPrice <= priceRange[1]
        // );
        filtered = filtered.filter((item) => {
    if (!item.dailyCapPrice) return true;
    return (
        item.dailyCapPrice >= priceRange[0] &&
        item.dailyCapPrice <= priceRange[1]
    );
});

        // Category filter
        if (selectedCategories.length > 0) {
            filtered = filtered.filter((item) =>
                selectedCategories.includes(item.category)
            );
        }

        // Search query (title or description)
        if (searchQuery.trim()) {
            const query = searchQuery.toLowerCase();
            filtered = filtered.filter(
                (item) =>
                    item.title?.toLowerCase().includes(query) ||
                    item.description?.toLowerCase().includes(query)
            );
        }

        // Distance filter (mock – if you have location coordinates, implement here)
        // For now we ignore actual distance. Keeping the slider as a UI placeholder.
        // You can later integrate with a geolocation library.

        // Sorting
        switch (sortBy) {
            case "newest":
                filtered.sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt));
                break;
            case "oldest":
                filtered.sort((a, b) => new Date(a.createdAt) - new Date(b.createdAt));
                break;
            case "price_asc":
                filtered.sort((a, b) => a.dailyCapPrice - b.dailyCapPrice);
                break;
            case "price_desc":
                filtered.sort((a, b) => b.dailyCapPrice - a.dailyCapPrice);
                break;
            case "name_asc":
                filtered.sort((a, b) => a.title.localeCompare(b.title));
                break;
            case "name_desc":
                filtered.sort((a, b) => b.title.localeCompare(a.title));
                break;
            default:
                break;
        }

        return filtered;
    }, [machinery, priceRange, selectedCategories, searchQuery, sortBy]);

    // Pagination slices
    const totalPages = Math.ceil(filteredMachinery.length / ITEMS_PER_PAGE);
    const paginatedItems = filteredMachinery.slice(
        (currentPage - 1) * ITEMS_PER_PAGE,
        currentPage * ITEMS_PER_PAGE
    );

    // Clear all filters
    const clearFilters = () => {
        setPriceRange([0, 10000]);
        setSelectedCategories([]);
        setSearchQuery("");
        setDistanceRange([0, 500]);
        setSortBy("newest");
        setCurrentPage(1);
    };

    // Category checkbox handler
    const handleCategoryChange = (category, checked) => {
        if (checked) {
            setSelectedCategories((prev) => [...prev, category]);
        } else {
            setSelectedCategories((prev) => prev.filter((c) => c !== category));
        }
    };

    if (loading) {
        return (
            <div className="bg-neutral-700 min-h-screen flex items-center justify-center">
                <p className="text-white text-xl">Loading machinery...</p>
            </div>
        );
    }

    if (error) {
        return (
            <div className="bg-neutral-700 min-h-screen flex items-center justify-center">
                <p className="text-red-400 text-xl">{error}</p>
            </div>
        );
    }

    return (
        <>
            {/* Hero section (unchanged) */}
            <section className="sm:min-h-48 min-h-40 bg-[url('/images/listing-bg.jpg')] bg-cover bg-center bg-no-repeat flex justify-center items-center relative">
                <div className="absolute bg-yellow-500/20 backdrop-blur-[2px] inset-0"></div>
                <div className="h-full w-full flex flex-col justify-center items-center relative z-10 space-y-2">
                    <h1 className="text-white text-3xl font-semibold">Listings</h1>
                    <Breadcrumb>
                        <BreadcrumbList>
                            <BreadcrumbItem>
                                <BreadcrumbLink href="/" className="text-gray-400 hover:text-yellowClr">Home</BreadcrumbLink>
                            </BreadcrumbItem>
                            <BreadcrumbSeparator />
                            <BreadcrumbItem>
                                <BreadcrumbPage className="text-gray-300">Listings</BreadcrumbPage>
                            </BreadcrumbItem>
                        </BreadcrumbList>
                    </Breadcrumb>
                </div>
            </section>

            <section className="bg-neutral-700 md:px-6 px-4">
                <div className="grid lg:grid-cols-5 md:grid-cols-4 sm:gap-4 gap-2">
                    {/* Sidebar Filters */}
                    <div className="md:block hidden h-fit top-16 sticky border-r border-neutral-700 py-6 pe-4">
                        <div className="flex justify-between items-start mb-2">
                            <p className="text-yellowClr font-medium">FILTERS</p>
                            <Button variant="outline" onClick={clearFilters} className="text-xs h-7 px-2 gap-1">
                                <X className="h-4" /> Clear
                            </Button>
                        </div>

                        {/* Price Range */}
                        <div className="border-b border-neutral-700 py-2 text-white">
                            <p className="font-semibold text-sm">Price Range (₹/day)</p>
                            <div className="space-y-4 mb-2">
                                <div>
                                    <output className="w-full text-sm font-medium tabular-nums flex justify-between">
                                        <span>₹{priceRange[0]}</span>
                                        <span>₹{priceRange[1]}</span>
                                    </output>
                                </div>
                                <Slider
                                    value={priceRange}
                                    min={0}
                                    max={10000}
                                    step={100}
                                    onValueChange={setPriceRange}
                                    aria-label="Price range slider"
                                />
                            </div>
                        </div>

                        {/* Category Filter (dynamic) */}
                        {availableCategories.length > 0 && (
                            <Accordion type="single" collapsible className="w-full border-b border-neutral-700">
                                <AccordionItem value="category">
                                    <AccordionTrigger className="text-white! font-semibold">Category</AccordionTrigger>
                                    <AccordionContent className="flex flex-col gap-3 text-balance text-white!">
                                        {availableCategories.map((cat) => (
                                            <div key={cat} className="flex items-center gap-2">
                                                <Checkbox
                                                    id={`cat-${cat}`}
                                                    checked={selectedCategories.includes(cat)}
                                                    onCheckedChange={(checked) => handleCategoryChange(cat, checked)}
                                                />
                                                <Label htmlFor={`cat-${cat}`} className="capitalize">{cat}</Label>
                                            </div>
                                        ))}
                                    </AccordionContent>
                                </AccordionItem>
                            </Accordion>
                        )}

                        {/* Distance Range (mock) */}
                        <div className="py-2 text-white">
                            <p className="font-semibold text-sm">Distance (km)</p>
                            <div className="space-y-4 mb-2">
                                <div>
                                    <output className="w-full text-sm font-medium tabular-nums flex justify-between">
                                        <span>{distanceRange[0]}<span className="text-xs">km</span></span>
                                        <span>{distanceRange[1]}<span className="text-xs">km</span></span>
                                    </output>
                                </div>
                                <Slider
                                    value={distanceRange}
                                    min={0}
                                    max={500}
                                    step={10}
                                    onValueChange={setDistanceRange}
                                    aria-label="Distance range slider"
                                />
                            </div>
                            <p className="text-xs text-gray-400 mt-1">(Coming soon: real distance filtering)</p>
                        </div>
                    </div>

                    {/* Main Content */}
                    <div className="lg:col-span-4 md:col-span-3 py-6">
                        <div className="bg-neutral-700 pb-4 flex sm:flex-row flex-col justify-between sm:items-start gap-2 md:static sticky top-[72px]">
                            <div>
                                <p className="text-white text-xl font-semibold">All Listings</p>
                                <p className="text-sm text-gray-400">
                                    Showing {paginatedItems.length} of {filteredMachinery.length} listings
                                </p>
                            </div>
                            <div className="flex gap-2">
                                <Input
                                    type="text"
                                    value={searchQuery}
                                    onChange={(e) => setSearchQuery(e.target.value)}
                                    className="bg-white focus-visible:ring-0 focus-visible:border-yellowClr"
                                    placeholder="Search by name or description"
                                />
                                <DropdownMenu modal={false}>
                                    <DropdownMenuTrigger asChild>
                                        <Button className="gap-2">
                                            <ArrowUpDown className="w-4 h-4" />
                                            <span className="sm:inline hidden">Sort by</span>
                                        </Button>
                                    </DropdownMenuTrigger>
                                    <DropdownMenuContent align="end" className="w-48">
                                        <DropdownMenuItem onClick={() => setSortBy("newest")}>
                                            <ClockArrowDown className="w-4 h-4" /> Newest to Oldest
                                        </DropdownMenuItem>
                                        <DropdownMenuItem onClick={() => setSortBy("oldest")}>
                                            <ClockArrowUp className="w-4 h-4" /> Oldest to Newest
                                        </DropdownMenuItem>
                                        <DropdownMenuSeparator />
                                        <DropdownMenuItem onClick={() => setSortBy("price_asc")}>
                                            <ArrowDownNarrowWide className="w-4 h-4" /> Price: Low to High
                                        </DropdownMenuItem>
                                        <DropdownMenuItem onClick={() => setSortBy("price_desc")}>
                                            <ArrowDownWideNarrow className="w-4 h-4" /> Price: High to Low
                                        </DropdownMenuItem>
                                        <DropdownMenuSeparator />
                                        <DropdownMenuItem onClick={() => setSortBy("name_asc")}>
                                            <ArrowDownAZ className="w-4 h-4" /> Name: A to Z
                                        </DropdownMenuItem>
                                        <DropdownMenuItem onClick={() => setSortBy("name_desc")}>
                                            <ArrowUpAZ className="w-4 h-4" /> Name: Z to A
                                        </DropdownMenuItem>
                                    </DropdownMenuContent>
                                </DropdownMenu>
                            </div>
                        </div>

                        {/* Machinery Grid */}
                        <div className="grid lg:grid-cols-4 md:grid-cols-3 sm:grid-cols-2 sm:gap-4 gap-2">
                            {paginatedItems.map((item) => (
                                <ProductCard
                                    key={item._id || item.id}
                                    data={item}
                                    isFavorite={isFavorite}
                                    onToggleFavorite={toggleFavorite}
                                />
                            ))}
                            {paginatedItems.length === 0 && (
                                <div className="col-span-full text-center py-12 text-gray-300">
                                    No machinery matches your filters.
                                </div>
                            )}
                        </div>

                        {/* Pagination Controls */}
                        {totalPages > 1 && (
                            <Pagination className="mt-6 text-white">
                                <PaginationContent>
                                    <PaginationItem>
                                        <PaginationPrevious
                                            href="#"
                                            onClick={(e) => {
                                                e.preventDefault();
                                                if (currentPage > 1) setCurrentPage(currentPage - 1);
                                            }}
                                            className={currentPage === 1 ? "pointer-events-none opacity-50" : ""}
                                        />
                                    </PaginationItem>
                                    {[...Array(Math.min(totalPages, 5))].map((_, idx) => {
                                        let pageNum;
                                        if (totalPages <= 5) pageNum = idx + 1;
                                        else if (currentPage <= 3) pageNum = idx + 1;
                                        else if (currentPage >= totalPages - 2) pageNum = totalPages - 4 + idx;
                                        else pageNum = currentPage - 2 + idx;
                                        if (pageNum > totalPages) return null;
                                        return (
                                            <PaginationItem key={pageNum}>
                                                <PaginationLink
                                                    href="#"
                                                    isActive={pageNum === currentPage}
                                                    onClick={(e) => {
                                                        e.preventDefault();
                                                        setCurrentPage(pageNum);
                                                    }}
                                                >
                                                    {pageNum}
                                                </PaginationLink>
                                            </PaginationItem>
                                        );
                                    })}
                                    {totalPages > 5 && currentPage < totalPages - 2 && (
                                        <PaginationItem>
                                            <PaginationEllipsis />
                                        </PaginationItem>
                                    )}
                                    <PaginationItem>
                                        <PaginationNext
                                            href="#"
                                            onClick={(e) => {
                                                e.preventDefault();
                                                if (currentPage < totalPages) setCurrentPage(currentPage + 1);
                                            }}
                                            className={currentPage === totalPages ? "pointer-events-none opacity-50" : ""}
                                        />
                                    </PaginationItem>
                                </PaginationContent>
                            </Pagination>
                        )}
                    </div>
                </div>
            </section>
        </>
    );
}

export default Page;