import {
    Breadcrumb,
    BreadcrumbItem,
    BreadcrumbLink,
    BreadcrumbList,
    BreadcrumbPage,
    BreadcrumbSeparator,
} from "@/components/ui/breadcrumb"
import { BadgeCheck, BadgeIndianRupee, Crown, HandHeart, HeartHandshake, Signature, Sparkles, Spool, Store } from "lucide-react";
import Image from "next/image"

export const metadata = {
    title: 'About Us - Ekcors',
    description: 'Generated by create next app',
}

const whyChooseUs = [
    {
        icon: <Signature className="h-6 w-6 text-white" />,
        title: "Wide Equipment Fleet",
        desc: "A comprehensive range of construction vehicles for small to large-scale projects.",
    },
    {
        icon: <Spool className="h-6 w-6 text-white" />,
        title: "Well-Maintained Machinery",
        desc: "Regularly serviced equipment to ensure performance, safety, and minimum downtime.",
    },
    {
        icon: <HandHeart className="h-6 w-6 text-white" />,
        title: "Flexible Rental Plans",
        desc: "Daily, weekly, and long-term rentals tailored to your project needs.",
    },
    {
        icon: <BadgeIndianRupee className="h-6 w-6 text-white" />,
        title: "Cost-Effective Solutions",
        desc: "High-value equipment access without the burden of ownership costs.",
    },
    {
        icon: <HeartHandshake className="h-6 w-6 text-white" />,
        title: "Trusted by Contractors",
        desc: "Preferred by builders, developers, and infrastructure companies across projects.",
    },
];


function page() {
    return (
        <>
            <section className="sm:min-h-48 min-h-40 bg-[url('/images/about-hero.jpg')] bg-cover bg-center bg-no-repeat flex justify-center
            items-center relative">
                <div className="absolute bg-yellow-500/20 backdrop-blur-[2px] inset-0"></div>
                <div className="h-full w-full flex flex-col justify-center items-center relative z-10 space-y-2">
                    <h1 className="text-white text-3xl font-semibold">About Us</h1>
                    <Breadcrumb>
                        <BreadcrumbList>
                            <BreadcrumbItem>
                                <BreadcrumbLink href="/" className={'text-gray-400 hover:text-yellowClr'}>Home</BreadcrumbLink>
                            </BreadcrumbItem>
                            <BreadcrumbSeparator />
                            <BreadcrumbItem>
                                <BreadcrumbPage className={'text-gray-300'}>About us</BreadcrumbPage>
                            </BreadcrumbItem>
                        </BreadcrumbList>
                    </Breadcrumb>
                </div>
            </section>
            <section className="px-4 md:px-6 bg-neutral-700">
                <div className="max-w-7xl mx-auto py-8 sm:py-12 md:py-16 lg:py-20 space-y-4 sm:text-lg text-white">
                    <p>
                        Welcome to <span className="text-yellowClr font-medium">EkCors</span>, your reliable partner for heavy construction vehicles and industrial machinery. We help builders, contractors, and infrastructure teams get the right equipment—on time and on budget.
                    </p>

                    <p>
                        Founded to simplify access to high-performance construction equipment, EkCors provides cranes, excavators, loaders, dumpers, and specialized machinery for short-term and long-term projects. Our focus is uptime, safety, and dependable service so your projects move forward without delays.
                    </p>
                    <Image
                        src="/images/about-2.jpg"
                        alt="about-us"
                        width={1000}
                        height={1000}
                        className="w-full rounded-2xl"
                    />
                </div>
            </section>
            <section className="px-4 md:px-6 bg-neutral-700">
                <div className="max-w-7xl mx-auto pb-8 sm:pb-12 md:pb-16 lg:pb-20">
                    <div className="grid md:gap-8 sm:gap-6 gap-4 lg:grid-cols-2">
                        <div className="flex flex-col justify-between rounded-2xl overflow-hidden bg-yellowClr">
                            <div className="flex justify-between gap-10 border-b border-white">
                                <div className="flex flex-col justify-between gap-14 py-6 pl-4 md:py-10 md:pl-8 lg:justify-normal">
                                    <h2 className=" text-4xl md:text-5xl text-white">Our <br /> Vision</h2>
                                </div>
                                <div className="md:1/3 w-2/5 shrink-0 rounded-r-lg">
                                    <Image width={500} height={500} src="/images/about-3.jpg" alt="Our Vision" loading="lazy" className="aspect-[4/5] w-full object-cover object-bottom" />
                                </div>
                            </div>
                            <div className="p-4 text-gray-100 md:p-8">
                                To become a trusted nationwide equipment rental partner, powering infrastructure growth by providing modern, well-maintained construction machinery with unmatched service reliability.
                            </div>
                        </div>
                        <div className="flex flex-col justify-between rounded-2xl overflow-hidden bg-yellowClr">
                            <div className="flex justify-between gap-10 border-b border-white">
                                <div className="flex flex-col justify-between gap-14 py-6 pl-4 md:py-10 md:pl-8 lg:justify-normal">
                                    <h2 className=" text-4xl md:text-5xl text-white">Our <br /> Mission</h2>
                                </div>
                                <div className="md:1/3 w-2/5 shrink-0 rounded-r-lg">
                                    <Image width={500} height={500} src="/images/about-4.jpg" alt="Our Mission" loading="lazy" className="aspect-[4/5] w-full object-cover object-top" />
                                </div>
                            </div>
                            <div className="p-4 text-gray-100 md:p-8">
                                We aim to deliver cost-effective equipment rental solutions with flexible terms, on-site support, and timely delivery—helping contractors complete projects faster, safer, and more efficiently.
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <section className="px-4 md:px-6 bg-neutral-700">
                <div className="max-w-7xl mx-auto pb-8 sm:pb-12 md:pb-16 lg:pb-20">
                    <h3 className="text-3xl font-medium  text-yellowClr lg:text-4xl">Why Choose Us?</h3>
                    <div className="md:mt-12 sm:mt-10 mt-6 grid gap-6 lg:grid-cols-3">
                        {whyChooseUs.map((item, index) => (
                            <div key={index} className="rounded-2xl bg-yellowClr/20 border border-yellowClr p-5">
                                <span className="mt-2 mb-6 flex size-12 items-center justify-center rounded-full bg-yellowClr">
                                    {item.icon}
                                </span>
                                <p className="mb-2 text-xl font-medium  text-yellowClr">{item.title}</p>
                                <p className="text-sm text-zinc-200">
                                    {item.desc}
                                </p>
                            </div>
                        ))}
                    </div>
                </div>
            </section>
            <section className="px-4 md:px-6 bg-neutral-700">
                <div className="max-w-7xl mx-auto pb-8 sm:pb-12 md:pb-16 lg:pb-20">
                    <div className="flex flex-wrap items-center">
                        <div className="w-full rounded-xl lg:w-1/2 lg:max-w-lg">
                            <div className="relative w-full max-w-lg">
                                <div className="relative">
                                    <Image width={1000} height={1000} className="mx-auto rounded-xl object-cover object-center" alt="About Us"
                                        src="/images/about-5.jpg" />
                                </div>
                            </div>
                        </div>
                        <div className="mt-12 flex flex-col items-start text-left md:mb-0 lg:w-1/2 lg:grow lg:pl-6 xl:mt-0 xl:pl-24">
                            <h4 className="md:mb-8 sm:mb-6 mb-4 text-4xl md:text-7xl lg:text-5xl  text-yellowClr">
                                About Us
                            </h4>
                            <div className="sm:space-y-4 space-y-2 text-white">
                                <p>
                                    <span className="font-medium">EkCors</span> was founded by
                                    <span className="font-medium"> an industry professional</span> with hands-on experience in construction operations and equipment management.
                                </p>

                                <p>
                                    With a strong understanding of project timelines and site challenges, the vision behind EkCors is simple:
                                    <span className="italic font-medium"> “Construction should never stop due to equipment unavailability.”</span>
                                </p>

                                <p>
                                    The company works closely with contractors and site engineers to recommend the right machinery for each job, ensuring efficiency and safety on every site.
                                </p>

                                <p className="italic font-light">
                                    From equipment selection to delivery coordination and support, every rental is handled with accountability and precision.
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <section className="px-4 md:px-6 bg-neutral-700">
                <div className="max-w-7xl mx-auto pb-8 sm:pb-12 md:pb-16 lg:pb-20">
                    <h5 className="text-3xl font-medium  text-yellowClr lg:text-4xl">Our Values</h5>
                    <div className="md:mt-12 sm:mt-10 mt-6 grid w-full grid-cols-1 md:gap-12 sm:gap-8 mx-auto md:grid-cols-2">
                        <div className="p-4">
                            <div className="flex items-center mb-3">
                                <div
                                    className="inline-flex items-center justify-center flex-shrink-0 w-12 h-12 mr-3 rounded-full bg-yellowClr">
                                    <Store size={24} className="text-white" />
                                </div>
                                <p className="text-xl font-semibold text-white tracking-wide ">Customer-first approach</p>
                            </div>
                            <p className="mx-auto text-base leading-relaxed text-gray-200">We prioritize project timelines, site safety, and reliable service at every stage.
                            </p>
                        </div>
                        <div className="p-4">
                            <div className="flex items-center mb-3">
                                <div
                                    className="inline-flex items-center justify-center flex-shrink-0 w-12 h-12 mr-3 rounded-full bg-yellowClr">
                                    <Sparkles size={24} className="text-white" />
                                </div>
                                <p className="text-xl font-semibold text-white tracking-wide ">Authenticity & trust</p>
                            </div>
                            <p className="mx-auto text-base leading-relaxed text-gray-200">
                                Transparent pricing, honest advice, and equipment you can depend on.
                            </p>
                        </div>
                        <div className="p-4">
                            <div className="flex items-center mb-3">
                                <div
                                    className="inline-flex items-center justify-center flex-shrink-0 w-12 h-12 mr-3 rounded-full bg-yellowClr">
                                    <Crown size={24} className="text-white" />
                                </div>
                                <p className="text-xl font-semibold text-white tracking-wide ">Creativity & innovation</p>
                            </div>
                            <p className="mx-auto text-base leading-relaxed text-gray-200">
                                Modern machinery and smarter rental solutions to meet evolving construction needs.
                            </p>
                        </div>
                        <div className="p-4">
                            <div className="flex items-center mb-3">
                                <div
                                    className="inline-flex items-center justify-center flex-shrink-0 w-12 h-12 mr-3 rounded-full bg-yellowClr">
                                    <BadgeCheck size={24} className="text-white" />
                                </div>
                                <p className="text-xl font-semibold text-white tracking-wide ">Consistent quality</p>
                            </div>
                            <p className="mx-auto text-base leading-relaxed text-gray-200">
                                Every vehicle undergoes strict checks to ensure peak performance on site.
                            </p>
                        </div>
                    </div>
                </div>
            </section>
        </>
    )
}

export default page
